# Generated by Django 5.2.7 on 2025-11-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='recordings.broadcast'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='recordings.session'),
        ),
        migrations.AddField(
            model_name='alert',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='keywords.keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('session', 'word')},
        ),
    ]
