# Generated by Django 5.1.7 on 2025-11-21 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcasts', '0001_initial'),
        ('keywords', '0001_initial'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='keywords_detected',
            field=models.ManyToManyField(blank=True, help_text='이 방송에서 감지된 키워드', related_name='broadcasts', to='keywords.keyword'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='recordings.session'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='recordings.session'),
        ),
    ]
