# Generated by Django 5.2.7 on 2025-11-09 06:02

import django.db.models.deletion
import recordings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audio Chunk',
                'verbose_name_plural': 'Audio Chunks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECORDING', 'Recording'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('EXPIRED', 'Expired')], default='RECORDING', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=recordings.models.default_expired_time)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recording Session',
                'verbose_name_plural': 'Recording Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(help_text='STT 변환된 안내방송 텍스트')),
                ('summary', models.TextField(blank=True, help_text='LLM 요약 결과')),
                ('confidence_avg', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='recordings.audiochunk')),
                ('keywords_detected', models.ManyToManyField(blank=True, help_text='이 방송에서 감지된 키워드', related_name='broadcasts', to='keywords.keyword')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='recordings.session')),
            ],
            options={
                'verbose_name': 'Broadcast Result',
                'verbose_name_plural': 'Broadcast Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='audiochunk',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='recordings.session'),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('total_broadcasts', models.IntegerField(default=0)),
                ('total_keywords', models.IntegerField(default=0)),
                ('accuracy_avg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='recordings.session')),
            ],
            options={
                'verbose_name': 'Session Transcript',
                'verbose_name_plural': 'Session Transcripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
